#!/bin/bash

for f in /home/kainatq/Downloads/aps/Beflix/seanime-web/public/icons/*
do
    w=$(identify -ping -format '%w' $f)
    echo $w
    convert /home/kainatq/Downloads/aps/Beflix/logo.png  -resize $w $f
done
