#!/bin/bash
terget=$1
res=$2
out=$3
filename=$(echo $(basename $out) | cut -f1 -d".")
echo "------->>" $filename "--------"
outpath=${out/%"$filename"}
echo !!!!$outpath!!!!
convert -resize $res $terget -quality 70%  $out
